import 'package:drift/drift.dart';
import 'package:xfin/database/accounts_dao.dart';
import 'package:xfin/database/bookings_dao.dart';
import 'package:xfin/database/tables.dart';

part 'app_database.g.dart';

// This file is now platform-agnostic.
// We'll use a separate file for the platform-specific implementation.

@DriftDatabase(tables: [Accounts, Bookings, StandingOrders, Goals], daos: [BookingsDao, AccountsDao])
class AppDatabase extends _$AppDatabase {
  AppDatabase(super.e);

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (m) async {
      await m.createAll();
    },
  );

  // The getters for the DAOs are automatically generated by Drift in the _$AppDatabase class.
  // We don't need to override them here.
}
